- name: Add epel-release repository
  yum:
    name: epel-release
    state: present

- name: Install nginx 
  yum:
    name: nginx
    state: present

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
    
